# Generated by Django 5.2.11 on 2026-04-11 08:41

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_add_theme_and_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='themes/previews/', validators=[apps.core.validators.validate_image_upload_size]),
        ),
    ]
