# Generated by Django 5.2.11 on 2026-02-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_carousel_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Image shown on the right in the welcome/hero section below the carousel.', null=True, upload_to='tenants/hero/'),
        ),
    ]
