# Generated by Django 5.2.11 on 2026-04-11 08:41

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_client_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/carousel/', validators=[apps.core.validators.validate_image_upload_size]),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tenants/carousel/', validators=[apps.core.validators.validate_video_upload_size]),
        ),
        migrations.AlterField(
            model_name='client',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/banners/', validators=[apps.core.validators.validate_image_upload_size]),
        ),
        migrations.AlterField(
            model_name='client',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Image shown on the right in the welcome/hero section below the carousel.', null=True, upload_to='tenants/hero/', validators=[apps.core.validators.validate_image_upload_size]),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/logos/', validators=[apps.core.validators.validate_image_upload_size]),
        ),
    ]
