# Generated by Django 5.2.11 on 2026-04-11 12:24

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_client_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='favicon',
            field=models.FileField(blank=True, help_text='Browser tab icon (.ico, PNG, or SVG). Max 512 KB.', null=True, upload_to='tenants/favicons/', validators=[apps.core.validators.validate_favicon_upload]),
        ),
    ]
