# Generated by Django 5.2.11 on 2026-04-19 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_contactsubmission'),
        ('tenants', '0016_client_font_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalPhoneCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_phone_captures', to='tenants.client')),
            ],
            options={
                'verbose_name': 'optional phone capture',
                'verbose_name_plural': 'optional phone captures',
                'ordering': ['-created_at'],
            },
        ),
    ]
