# Generated by Django 5.2.11 on 2026-04-11 08:41

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_and_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/products/', validators=[apps.core.validators.validate_image_upload_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='catalog/product_images/', validators=[apps.core.validators.validate_image_upload_size]),
        ),
    ]
