# Generated by Django 5.2.11 on 2026-04-11 09:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_upload_size_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional original / MRP. If higher than sale price, the site shows a discount.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Sale price — what the customer pays.', max_digits=12),
        ),
    ]
