# Generated by Django 5.2.11 on 2026-04-12 11:27

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_spotlight',
            field=models.BooleanField(default=False, help_text='Show this category on the home Spotlight strip (up to four, ordered below).'),
        ),
        migrations.AddField(
            model_name='category',
            name='spotlight_discount_text',
            field=models.CharField(blank=True, help_text='Large offer line, e.g. 15% OFF.', max_length=40),
        ),
        migrations.AddField(
            model_name='category',
            name='spotlight_headline',
            field=models.CharField(blank=True, help_text='Small caps line above the offer, e.g. Festival sale.', max_length=120),
        ),
        migrations.AddField(
            model_name='category',
            name='spotlight_image',
            field=models.ImageField(blank=True, help_text='Portrait-style photo works best. Max 3 MB.', null=True, upload_to='catalog/category_spotlight/', validators=[apps.core.validators.validate_image_upload_size]),
        ),
        migrations.AddField(
            model_name='category',
            name='spotlight_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in Spotlight.'),
        ),
        migrations.AddField(
            model_name='category',
            name='spotlight_subtitle',
            field=models.CharField(blank=True, help_text='Line under the offer. Blank uses the category name.', max_length=120),
        ),
        migrations.AddField(
            model_name='category',
            name='spotlight_tag_style',
            field=models.CharField(blank=True, choices=[('', 'No corner tag'), ('price', 'Green — price / promo text'), ('code', 'Green — code / SKU'), ('new', 'White — badge text')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='category',
            name='spotlight_tag_text',
            field=models.CharField(blank=True, help_text='Text for the corner tag (e.g. From ₹1,299 or SKU code).', max_length=80),
        ),
        migrations.AddField(
            model_name='category',
            name='spotlight_upto_label',
            field=models.CharField(blank=True, default='', help_text='Usually “Upto”. Leave blank to use “Upto”.', max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='spotlight_video',
            field=models.FileField(blank=True, help_text='Optional. If set, video plays instead of the image. Max 15 MB, MP4 only.', null=True, upload_to='catalog/category_spotlight/video/', validators=[apps.core.validators.validate_video_upload_size, django.core.validators.FileExtensionValidator(['mp4'], message='Spotlight video must be an MP4 file.')]),
        ),
    ]
